### ISSUE TITLE
V1.2.6 causes ErrorException in HasOneOrMany.php line 12

### ISSUE THREAD

**Issue by marlongichie** [Vinelab/NeoEloquent#103]
Using Laravel 5, after updating to v1.2.6, code which functioned perfectly now throws the error below when working with any model that has relationships.

```
Declaration of Vinelab\NeoEloquent\Eloquent\Relations\HasOneOrMany::saveMany() should be compatible with Illuminate\Database\Eloquent\Relations\HasOneOrMany::saveMany(array $models)
```

**Comment by Mulkave** [comment]
It's weird how these errors keep repeating although they've been merged in the past.

**Comment by tomb10516** [comment]
Mulkave,

This issue may be deeper than it looks at first glance.  This is the same issue as #104 which I opened because I didn't see #103 in time to not make a duplicate issue.

Tomorrow I'll keep trying to unravel the best way to deal with the differences between Eloquent 5.0 and 5.1.  5.0 wants the array type hint, and 5.1 doesn't.  The way the composer.json is written in v1.2.6 illuminate/database 5.1 is what gets installed.

**Comment by tomb10516** [comment]
I just saw your commit 77344ea58fd  I still think this might not be backwards compatible with older versions of illuminate/database.  Please let me know if I'm wrong so I don't waste time tomorrow!
