### ISSUE TITLE
Ubuntu 16.04 - Problem installing NeoEloquent

### ISSUE THREAD

**Issue by gburu98** [Vinelab/NeoEloquent#177]
Team Vinelab good day,
I'm migrating to Ubuntu 16.04, and I can not install neoeloquent:

* Ubuntu 16.04
* PHP 7.0.11
* Laravel 5.2.31

I need php packages for operation, how may i install the following packages? (image)
![neoelocuent](https://cloud.githubusercontent.com/assets/12548796/18815147/0999a71a-82fe-11e6-90eb-8c71e522a279.png)

**Comment by Mulkave** [comment]
@heydavid713 can you please give some insight on the above?

**Comment by heydavid713** [comment]
@gburu98 did you already try `sudo apt install php-curl`?

**Comment by gburu98** [comment]
Problem solved, missing me (**apt-get install php-curl**), thank you very much for the solution !!
![solved](https://cloud.githubusercontent.com/assets/12548796/18815986/be548a8c-8315-11e6-9003-884d3875c643.png)

**Comment by Mulkave** [comment]
Great 👍

**Comment by DeltaBravo** [comment]
All this us saying is that you need to enable curl in PHP--specifically for
the CLI PHP configuration. Try searching the Web for "enable curl PHP
Ubuntu" and "enable module PHP CLI Ubuntu".

On Sep 25, 2016 07:57, "Gaston Buruchaga" <notifications@github.com> wrote:

Team Vinelab good day,
I'm migrating to Ubuntu 16.04, and I can not install neoeloquent:

   - Ubuntu 16.04
   - PHP 7.0.11
   - Laravel 5.2.31

I need php packages for operation, how may i install the following
packages? (image)
[image: neoelocuent]
<https://cloud.githubusercontent.com/assets/12548796/18815147/0999a71a-82fe-11e6-90eb-8c71e522a279.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Vinelab/NeoEloquent/issues/177>, or mute the thread
