### ISSUE TITLE
I got this error when use NeoEloquent in Laravel 5.4

### ISSUE THREAD

**Issue by yavand** [Vinelab/NeoEloquent#240]
Hi, Sorry for my bad English.
when i use this plugin with laravel 5.3 no problem was occurd but in use with Laravel 5.4 i got this Error.
whats the problem?
this problem returns to Pagination and when i dont use pagination i dont have any problem.

SyntaxException: Variable `article` not defined (line 1, column 62 (offset: 61))
"MATCH (article:`Article`:`Content`) RETURN count(*) ORDER BY article.created_at DESC"

**Comment by dimitriSpb** [comment]
Hi,

I have same error and I know why (but not solution) : 
Prolem comes from when we use paginate + order by clause, because paginate produice 2 queries : 
 - 1 for count all result with filter
- another for search only query with pagination (and filters, order by ...)

But in first query (count all result), there are order by to added and we need to remove it .


Example : 
`$collection = User::orderBy('id', 'asc')->paginate(2);`
Error => SyntaxException: Variable `user` not defined (line 1, column 79 (offset: 78))\n\"MATCH (user:`User`) WHERE user.deleted_at is null RETURN count(*) ORDER BY id(user) ASC\"\n 

Query MATCH (user:`User`) WHERE user.deleted_at is null RETURN count(*) ORDER BY id(user) ASC need to be MATCH (user:`User`) WHERE user.deleted_at is null RETURN count(*) 

`$collection = User::paginate(2);` => OK


Anybody have a solution or can resolve this problem ?


I'm using Lumen (5.4.6) 
package version "vinelab/neoeloquent": "1.4.*"

PS : In documentation, for laravel 5.4 you say to use 
{
    "require": {
        "vinelab/neoeloquent": "dev-laravel5.4"
    }
}
But dev-laravel5.4 not exist

Thanks

**Comment by Mulkave** [comment]
Is this still valid? Compatibility with 5.4 was pushed long ago. Please try again and re-open if still exists.
