### ISSUE TITLE
Re: dev-laravel5.4 

### ISSUE THREAD

**Issue by ashbeats** [Vinelab/NeoEloquent#248]
Has this branch been renamed? 
```
"vinelab/neoeloquent": "dev-laravel5.4"
```

It worked previously, but now Composer update is not able to resolve the package.

**Comment by dimitriSpb** [comment]
Hi,

This branch don't exist.

I use it (last stable branch) :
` "vinelab/neoeloquent": "1.4.*",`

**Comment by alexislefebvre** [comment]
Hi,
it looks like the README.md should be updated: https://github.com/Vinelab/NeoEloquent/blob/acff98c1b325e6333924a8f31526682a0e235a9b/README.md#54

Since support of Laravel 5.4 has been added in the [1.4 branch](https://github.com/Vinelab/NeoEloquent/releases/tag/v1.4.3), this may be rewritten as this:

> 5.4 / 5.3
> 
> ```
> {
>     "require": {
>         "vinelab/neoeloquent": "1.4.*"
>     }
> }
> ```

**Comment by Mulkave** [comment]
Readme has been updated to showcase the exact supported framework versions: https://github.com/Vinelab/NeoEloquent#laravel-5

Please let me know if this answers your concerns and add any questions here. Closing for now.
