### ISSUE TITLE
Can't get models through a property of name 'id'

### ISSUE THREAD

**Issue by brazenvoid** [Vinelab/NeoEloquent#30]
I don't use the auto incremented id field attached to each node but define another property named id and store a generated number in it. The problem is that, if I do a query on that property to like get the node with a specific id, it returns null while running a cypher query in the neo4j console returns the correct node.

For example;
NeoEloquent query: User::where('id',100000494478771)->get()->first(); // returns null
Cypher query: MATCH (n:User{id:100000494478771}) RETURN n // returns the node

**Comment by Mulkave** [comment]
Closing this issue since it's a requirement to not use the property 'id' as a custom property. You may name it anything else like `uuid` or `guid` as previously stated, also would like to mention that it is recommended to always use the `getKey()` Eloquent method to reference the primary key instead of targeting it directly.
