### ISSUE TITLE
Strange error with autoincrement id

### ISSUE THREAD

**Issue by thanosalexander** [Vinelab/NeoEloquent#300]
I have a Post model and when i create a new one
```
App\Post::create([
     'body'=>'test'
])
```
i receive strange ids
 eg for past posts i have id 1186514 and for a newer one i have 1186487 which is lower , so i face huge problem in sorting

**Comment by holix** [comment]
Hey,

this is due to neo4j internal ids. As you can read here:
https://stackoverflow.com/questions/30753560/should-we-use-the-neo4j-internal-id
it is not recommended to use internal ids, as they can be reused, like it happened in your example.
Obviously they are only reused after node/relationship is deleted.

You should either associate your own ids to nodes, and use them as autoincrement, or sort them using created_at column.

**Comment by thanosalexander** [comment]
Hi .. sure its a solution but it's not too much safe as maybe some other instance will be created at same time (second level).. so which one will be sorted first?
