### ISSUE TITLE
Store session in database(neo4j)

### ISSUE THREAD

**Issue by belt-basya** [Vinelab/NeoEloquent#343]
Hello everyone, 
               
I am new to `neo4j`. I have built a test app. It is a simple `laravel-neo4j` user login and register app. Everything works fine. But I want to store the session details in the database, not in the file. So I have tried [this](https://stackoverflow.com/questions/37439721/unable-to-store-session-in-database-in-laravel-5-2/39240363#39240363) method and got the `Undefined offset: 0` error. So please help me. I have given the link for docker and commands to run it. Please run this and help me to solve this problem. Right now the session is storing in the file. First, register an account then use that account for login. Thank you.

docker: https://drive.google.com/file/d/1q0Cd6QwaVnqyoWeUOHWnodWNCL24MBrj/view?usp=sharing

**Command to run docker file**
```
./docker_compose.sh build
./docker_compose.sh up
```

**URLs**

Front-end: http://0.0.0.0:8081/

Login: http://0.0.0.0:8081/login

Register: http://0.0.0.0:8081/register

Neo4j: http://0.0.0.0:8083/browser/

**Login credentials for neo4j:**
```
Username: neo4j
Password: root
```

**Comment by Mulkave** [comment]
@belt-basya thank you for your patience waiting for so long, and sorry for the delay on this, the activity on the package has been stale for a while but we're back in activity and just updated to support Laravel 8 with NE version 1.8.

Otherwise, if you're using another version of Laravel please update your package to get the latest update that includes the official [Neo4j-php driver](https://github.com/neo4j-php/neo4j-php-client/).

After that, please try again and let us know in another issue if this persists. Thank you!
