### ISSUE TITLE
Examples on deletion,and Relations properties

### ISSUE THREAD

**Issue by k-timy** [Vinelab/NeoEloquent#39]
Could you add some examples to documentaion or on problems below:
1.How do you delete a node?
2.How do you delete a node's relations?
3.How do you search in database based on a specific property of a node? for example,suppose that you have 10 nodes,each one stores name,email,and phone number of a person,how do you find the node that it's name property is "john"?
4.How do you define and access properties of relations?
It would be great if you added some examples to documentation.thanks in advance.

**Comment by Mulkave** [comment]
The reason why these examples are not in the documentation is because they work the same thing as they do in Eloquent so you may look at the [Eloquent documentation](http://laravel.com/docs/4.2/eloquent) for that regard.

One thing to note about deleting nodes is that when a node has relations they need to be deleted first. To do that you need to fetch the *edges* and delete them. Here's a generic example:

```php
$relations = $model->relationship()->edges();

foreach ($relations as $relation) {
    $relation->delete();
}

$model->delete();
```

This is the behaviour of Neo4j similar to deleting a record with foreign keys reference in MySQL.

Regarding question number 4 please check [the edges part of the documentation](https://github.com/Vinelab/NeoEloquent#edges).

Hope these resources make it clear for you.

**Comment by k-timy** [comment]
Thank you so much.It helped.
